branches:
  except:
    - gh-pages

env:
  global:
    - GH_REPO_NAME: <your_repo>
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
    - GH_REPO_REF: github.com/alesiong/appveyor-test.git
    - secure: "jFXoQCyGKdP1A9gPTVZUZkF2+chev25/QITN0KnnlCyB205WB1pNBtRbeV3YonY0+/vyL++6PCu9+T65+/GZaT3RA2uPVqgVkX4RxKkvDmECTC/QgKGcvgp06EOp5Y9tfOhnTd/+xbbZzwT1uBDO83YN3eruCQ9rsxa+AIN3DmrvVYy/QXU9CR8x0XDfWN19tYH3k/wY+EKTYLr65zfP6ZuFWAcqqzNM4J2NT8h4jZBdXNz6N5SlR7erN8XNNDq5mle4UvFLlUcimoMJ2isJBLk8uD8lJmXfaQ9ho4CYd3PKkg5SDoca77IxTQyPB3dF2zgbh57Y7nDG3YeKoRhzykI6qVDqF8r8ThOilqGn0IZfjD5OrVRwTH7Qy51UmfpXlHDeNthNxInwdeUrT6Bwic5F85gUB1N+KTVbTJHwogvBy+fPGjf407RZCVeUDWB6ojkb+h7yK3pG0LK67TiYynfFDY/hIr4ktS9GFTvALF/ushVEo1uIgKNRpJqQTcQ/Gh6QdnvC3CZ83W9ig8/bMjkkrXh8makbrmPzVV6eDGy6BRHLsa3thDlHNhiO5Eg/Sgl1fqnI49k8HkgHbzBGEHOaPzpfGL0iQGr0kuzdnrtF9wgwt/XmQrh7RBhdWPwQJYoQRUNUap8Ns9V0fMbTs4dyB9kSdJgUQRBKL1BNbhw="


install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
- if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7"
  CC="clang-3.7"; fi
- echo ${PATH}
- echo ${CXX}
- "${CXX} --version"
- "${CXX} -v"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - gcc-4.9
    - g++-4.9
    - clang-3.7
    - doxygen
    - doxygen-doc
    - doxygen-latex
    - doxygen-gui
    - graphviz

os:
- linux
- osx
language: cpp
compiler:
- gcc
- clang
script:
- mkdir build && cd build
- cmake ..
- make && make test
notifications:
  email: false
sudo: false

after_success: |
  if  [ "$TRAVIS_OS_NAME" = "linux" ]; then
    tar -czvf linux-gcc.tar.gz libdata.a
    if [ "$CXX" = "g++-4.9" ]; then
      cd $TRAVIS_BUILD_DIR
      chmod +x document.sh
      ./document.sh
    fi
  else
    tar -czvf macos-clang.tar.gz libdata.a
  fi

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: SaduPOIhHxBGZ9Qj9YOrU4nuSh3m24vwDUHEzQXgROV9W1rdL8aZvSWwMvGsq4dv0XB8s+nQwPL7pfoj5lo/XoZqtmcZ9ExRwtMTLYZlaVXHZj9gg0udDR4uSnIU64+zndq0GY43f3RzhICEw0H7yNXiUKwvoXJYov9CfZbV8F/qYTR149ZyBJqLq1V56SXjMvMhQ79olLQnzwwcvVqS46et6IO15siOWH2U5Qb/QOZrk6GKUZgRkxlEOCSJN+2nzO8JrEY8QKomXwoucaWRBOl4aU+/sDwkaCfgUK1XdOdm68uWtq5Ix+lMSk0DZ0U/JcM58dndkXhG8NEdgIqyrzXd+qjhCAGHm4B0FlE+keeDO5RtZXxtIQZS2zZDlRwobutYxvxKphpYICxmbqEzzaUp0FzNMZ6yBHh4mEOjUl21Q6jl4gztAwMgvtI00rhDZPIs5Cw3G4ObGvMON4h5Jogp7NM/OlYz9X9pOtT+J8+P+S6/5NwmP7qu5/5IS+HVUCCsxRliWQvGDWQMrVnePV9lCIqIXeTM7aniP2qsJgsahJiIJSVlKb8MkUTiO5e62K0Hnvmow8fmbTeVMV4kmisdgsTTTIed4XZirqY+TQFFfmR/NGhtZZGPcjmSKY/tbxzGbdRdgzSP7diGBaPmg1Eg/dTt3LIuAS36fsuf3qk=
  file_glob: true
  file: "*.tar.gz"
  on:
    repo: alesiong/appveyor-test
    all_branches: true
    condition: " ($TRAVIS_TAG) && ((( $TRAVIS_OS_NAME = linux ) && ( $CXX = g++-4.9 ) ) || ( $CXX = clang++ )) "
    tag: true
