# shallow clone
clone_depth: 10

os: Visual Studio 2015

platform:
  - x64
  - Win32

environment:
  matrix:
  # - Toolset: v140
  - Toolset: v120
  - Toolset: v110
  - Toolset: v100

configuration:
  - Debug

install:
  - git submodule update --init --recursive

before_build:
- ps: |
    md build
    cd build
    $generator = switch ($env:TOOLSET)
    {
        "v140" {"Visual Studio 14 2015"}
        "v120" {"Visual Studio 12 2013"}
        "v110" {"Visual Studio 11 2012"}
        "v100" {"Visual Studio 10 2010"}
        "mingw" {"MinGW Makefiles"}
        "msys" {"MSYS Makefiles"}
    }
    if (($env:PLATFORM -eq "x64") -and ($env:TOOLSET -ne "mingw") -and ($env:TOOLSET -ne "msys"))
    {
        $generator = "$generator Win64"
    }
    cmake -G "$generator"  ..
    cd ..

build:
  verbosity: minimal
  # project: build/data.sln

build_script:
- ps: |
    if (($env:TOOLSET -eq "v100") -and ($env:PLATFORM -eq "x64"))
    {
        return
    }
    cd build
    & cmake --build . --config $env:CONFIGURATION
    if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
    }
